name: test

on:
  workflow_run:
    workflows: [ci]
    types:
      - completed

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Pull Docker image
        run: docker pull mjbourgeon/fastdocx-api:latest

      - name: Run tests
        run: docker run --rm mjbourgeon/fastdocx-api /bin/bash -c "pip install -r requirements.dev.txt ; pytest -v app/"