name: test

on:
  workflow_run:
    workflows: [ci]
    types:
      - completed

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4  # required for codecov
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Pull Docker image
        run: docker pull mjbourgeon/fastdocx-api:latest

      - name: Run container in detached mode
        run: docker run -d --name fastdocxapi mjbourgeon/fastdocx-api sleep infinity

      - name: Install dependencies
        run: docker exec $(docker ps -aqf "name=fastdocxapi") pip install -r requirements.dev.txt

      - name: Run tests
        run: docker exec $(docker ps -aqf "name=fastdocxapi") pytest --cov=app/ app/ --cov-report=xml
      
      - name: Copy coverage file before upload
        run: docker cp $(docker ps -aqf "name=fastdocxapi"):/coverage.xml .

      - name: Cleanup
        run: docker stop fastdocxapi && docker rm fastdocxapi

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          disable_search: true
          verbose: true
